SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROC [dbo].[Keystats_AuditorActivity_VsBFCAvg_Load]  
    (  
      @BEGINDATE DATETIME ,  
      @ENDDATE DATETIME ,  
      @USERNAME VARCHAR(50) ,  
      @FILTERTYPE VARCHAR(3)  
    )  
AS  
    BEGIN    
    
        SET @ENDDATE = DATEADD(S, -1, DATEADD(DAY, 1, @ENDDATE));      
        IF OBJECT_ID('TempDB..#AuditorActivity') IS NOT NULL  
            BEGIN      
                DROP TABLE #AuditorActivity;      
            END;      
      
        DECLARE @AuditorIndividualStats AS TABLE  
            (  
              sortOrder INT ,  
              [index] INT ,  
              headerName VARCHAR(75) ,  
              className VARCHAR(15) ,  
              userName VARCHAR(15) ,  
              fullName VARCHAR(75) ,  
              lName VARCHAR(15) ,  
              IsMiscellaneous BIT ,  
              startDate VARCHAR(10) ,  
              genTotalHours INT ,  
              genExpectedHours DECIMAL(10, 2) ,  
              genTotalPay DECIMAL(10, 2) ,  
              genAvgPayPerHour DECIMAL(10, 2) ,  
              desTotalHours DECIMAL(10, 2) ,  
              desTotalDesigns INT ,  
              desTotalCharacters INT ,  
              desDesignsPerHour DECIMAL(10, 2) ,  
              desCharPerHour DECIMAL(10, 2) ,  
              desCostPerDesign DECIMAL(10, 2) ,  
              keyTotalHours DECIMAL(10, 2) ,  
              keyDesignsCleaned INT ,  
              keyDesignsPerHour DECIMAL(10, 2) ,  
              keyCostPerDesign DECIMAL(10, 2) ,  
              less20TotalHours DECIMAL(10, 2) ,  
              less20DesignsCleaned INT ,  
              less20DesignsPerHour DECIMAL(10, 2) ,  
              less20CostPerDesign DECIMAL(10, 2) ,  
              MathTest INT ,  
              mathAccuracy INT ,  
              numberMatching INT ,  
              numberAccuracy INT ,  
              wordMatching INT ,  
              wordAccuracy INT ,  
              typingSpeed INT ,  
              typingAccuracy INT ,  
              typingTestKeyStrokes INT ,  
              jobSpecQues INT ,  
              beaconScore INT ,  
              ficoScore INT ,  
              totalCall INT ,  
              totalCallIn INT ,  
              totalCallOut INT ,  
              totalCallInt INT ,  
              avgCalls DECIMAL(10, 2) ,  
              avgCallDurationMin DECIMAL(10, 2) ,  
              dailyStart VARCHAR(5) ,  
              dailyEnd VARCHAR(5) ,  
              totalActiveHours DECIMAL(10, 2) ,  
              nonWorkHours DECIMAL(10, 2) ,  
              keyStroke INT ,  
              totalEmails INT ,  
              startdateminute INT ,  
              enddateminute INT  
            );      
     
          
        DECLARE @AuditorIndividualDrillDown AS TABLE  
            (  
              sortOrder INT ,  
              [index] INT ,  
              headerName VARCHAR(75) ,  
              className VARCHAR(15) ,  
              userName VARCHAR(15) ,  
              fullName VARCHAR(75) ,  
              lName VARCHAR(15) ,  
              IsMiscellaneous BIT ,  
              startDate VARCHAR(10) ,  
              genTotalHours INT ,  
              genExpectedHours DECIMAL(10, 2) ,  
              genTotalPay DECIMAL(10, 2) ,  
              genAvgPayPerHour DECIMAL(10, 2) ,  
              desTotalHours DECIMAL(10, 2) ,  
              desTotalDesigns INT ,  
              desTotalCharacters INT ,  
              desDesignsPerHour DECIMAL(10, 2) ,  
              desCharPerHour DECIMAL(10, 2) ,  
              desCostPerDesign DECIMAL(10, 2) ,  
              keyTotalHours DECIMAL(10, 2) ,  
              keyDesignsCleaned INT ,  
              keyDesignsPerHour DECIMAL(10, 2) ,  
              keyCostPerDesign DECIMAL(10, 2) ,  
              less20TotalHours DECIMAL(10, 2) ,  
              less20DesignsCleaned INT ,  
              less20DesignsPerHour DECIMAL(10, 2) ,  
              less20CostPerDesign DECIMAL(10, 2) ,  
              MathTest TINYINT ,  
              mathAccuracy TINYINT ,  
              numberMatching TINYINT ,  
              numberAccuracy TINYINT ,  
              wordMatching TINYINT ,  
              wordAccuracy TINYINT ,  
              typingSpeed TINYINT ,  
              typingAccuracy TINYINT ,  
              typingTestKeyStrokes TINYINT ,  
              jobSpecQues TINYINT ,  
              beaconScore TINYINT ,  
              ficoScore TINYINT ,  
              totalCall INT ,  
              totalCallIn INT ,  
              totalCallOut INT ,  
              totalCallInt INT ,  
              avgCalls DECIMAL(10, 2) ,  
              avgCallDurationMin DECIMAL(10, 2) ,  
              dailyStart VARCHAR(22) ,  
              dailyEnd VARCHAR(22) ,  
              totalActiveHours DECIMAL(10, 2) ,  
              nonWorkHours DECIMAL(10, 2) ,  
              keyStroke INT ,  
              totalEmails INT ,  
              startdateminute INT ,  
              enddateminute INT  
            );     
    
        INSERT  INTO @AuditorIndividualStats  
                ( sortOrder ,  
                  [index] ,  
                  headerName ,  
                  className ,  
                  userName ,  
                  fullName ,  
                  lName ,  
                  IsMiscellaneous ,  
                  startDate ,  
                  genTotalHours ,  
                  genExpectedHours ,  
                  genTotalPay ,  
                  genAvgPayPerHour ,  
                  desTotalHours ,  
                  desTotalDesigns ,  
                  desTotalCharacters ,  
                  desDesignsPerHour ,  
                  desCharPerHour ,  
                  desCostPerDesign ,  
                  keyTotalHours ,  
                  keyDesignsCleaned ,  
                  keyDesignsPerHour ,  
                  keyCostPerDesign ,  
                  less20TotalHours ,  
                  less20DesignsCleaned ,  
                  less20DesignsPerHour ,  
                  less20CostPerDesign ,  
                  MathTest ,  
                  mathAccuracy ,  
                  numberMatching ,  
                  numberAccuracy ,  
                  wordMatching ,  
                  wordAccuracy ,  
                  typingSpeed ,  
                  typingAccuracy ,  
                  typingTestKeyStrokes ,  
                  jobSpecQues ,  
                  beaconScore ,  
                  ficoScore ,  
                  totalCall ,  
                  totalCallIn ,  
                  totalCallOut ,  
                  totalCallInt ,  
                  avgCalls ,  
                  avgCallDurationMin ,  
                  dailyStart ,  
                  dailyEnd ,  
                  totalActiveHours ,  
                  nonWorkHours ,  
                  keyStroke ,  
                  totalEmails ,  
                  startdateminute ,  
                  enddateminute    
                )  
                EXEC dbo.Keystats_AuditorActivity_Individualstats_Load @BEGINDATE = @BEGINDATE, -- datetime    
                    @ENDDATE = @ENDDATE, -- datetime    
                    @FILTERTYPE = @FILTERTYPE; -- varchar(3)    
           
    
        INSERT  INTO @AuditorIndividualDrillDown  
                ( [index] ,  
                  headerName ,  
                  startDate ,  
                  fullName ,  
                  genTotalHours ,  
                  genExpectedHours ,  
                  genTotalPay ,  
                  genAvgPayPerHour ,  
                  desTotalHours ,  
                  desTotalDesigns ,  
                  desTotalCharacters ,  
                  desDesignsPerHour ,  
                  desCharPerHour ,  
                  desCostPerDesign ,  
                  keyTotalHours ,  
                  keyDesignsCleaned ,  
                  keyDesignsPerHour ,  
                  keyCostPerDesign ,  
                  less20TotalHours ,  
                  less20DesignsCleaned ,  
                  less20DesignsPerHour ,  
                  less20CostPerDesign ,  
                  totalCall ,  
                  totalCallIn ,  
                  totalCallOut ,  
   totalCallInt ,  
                  avgCalls ,  
                  avgCallDurationMin ,  
                  dailyStart ,  
                  dailyEnd ,  
                  totalActiveHours ,  
                  nonWorkHours ,  
                  keyStroke ,  
                  totalEmails ,  
                  startdateminute ,  
                  enddateminute     
                )  
                EXEC dbo.Keystats_AuditorActivity_IndividualDrillDown_Load @BEGINDATE = @BEGINDATE, -- datetime      
                    @ENDDATE = @ENDDATE, -- datetime      
                    @USERNAME = @USERNAME;         
    
        SELECT  *  
        INTO    #AuditorActivity  
        FROM    ( SELECT    1 sortOrder ,  
                            1 [index] ,  
                            COALESCE([@AuditorIndividualStats].userName,  
                                     @USERNAME) + '<br/> &nbsp;' headerName ,  
                            '' className ,  
                            COALESCE([@AuditorIndividualStats].userName,  
                                     @USERNAME) userName ,  
                            [@AuditorIndividualDrillDown].fullName ,  
                            [@AuditorIndividualStats].lName ,  
                            [@AuditorIndividualStats].IsMiscellaneous ,  
                            [@AuditorIndividualStats].startDate ,  
                            [@AuditorIndividualDrillDown].genTotalHours ,  
                            [@AuditorIndividualDrillDown].genExpectedHours ,  
                            [@AuditorIndividualDrillDown].genTotalPay ,  
                            [@AuditorIndividualDrillDown].genAvgPayPerHour ,  
                            [@AuditorIndividualDrillDown].desTotalHours ,  
                            [@AuditorIndividualDrillDown].desTotalDesigns ,  
                            [@AuditorIndividualDrillDown].desTotalCharacters ,  
                            [@AuditorIndividualDrillDown].desDesignsPerHour ,  
                            [@AuditorIndividualDrillDown].desCharPerHour ,  
                            [@AuditorIndividualDrillDown].desCostPerDesign ,  
                            [@AuditorIndividualDrillDown].keyTotalHours ,  
                            [@AuditorIndividualDrillDown].keyDesignsCleaned ,  
                            [@AuditorIndividualDrillDown].keyDesignsPerHour ,  
                            [@AuditorIndividualDrillDown].keyCostPerDesign ,  
                            [@AuditorIndividualDrillDown].less20TotalHours ,  
                            [@AuditorIndividualDrillDown].less20DesignsCleaned ,  
                            [@AuditorIndividualDrillDown].less20DesignsPerHour ,  
                            [@AuditorIndividualDrillDown].less20CostPerDesign ,  
                            [@AuditorIndividualStats].MathTest ,  
                            [@AuditorIndividualStats].mathAccuracy ,  
                            [@AuditorIndividualStats].numberMatching ,  
                            [@AuditorIndividualStats].numberAccuracy ,  
                            [@AuditorIndividualStats].wordMatching ,  
                            [@AuditorIndividualStats].wordAccuracy ,  
                            [@AuditorIndividualStats].typingSpeed ,  
                            [@AuditorIndividualStats].typingAccuracy ,  
                            [@AuditorIndividualStats].typingTestKeyStrokes ,  
                            [@AuditorIndividualStats].jobSpecQues ,  
                            [@AuditorIndividualStats].beaconScore ,  
                            [@AuditorIndividualStats].ficoScore ,  
                            [@AuditorIndividualDrillDown].totalCall ,  
                            [@AuditorIndividualDrillDown].totalCallIn ,  
                            [@AuditorIndividualDrillDown].totalCallOut ,  
                            [@AuditorIndividualDrillDown].totalCallInt ,  
                            [@AuditorIndividualDrillDown].avgCalls ,  
                            [@AuditorIndividualDrillDown].avgCallDurationMin ,  
                            [@AuditorIndividualDrillDown].dailyStart ,  
                            [@AuditorIndividualDrillDown].dailyEnd ,  
                            [@AuditorIndividualDrillDown].totalActiveHours ,  
                            [@AuditorIndividualDrillDown].nonWorkHours ,  
                            [@AuditorIndividualDrillDown].keyStroke ,  
                            [@AuditorIndividualDrillDown].totalEmails ,  
                            [@AuditorIndividualDrillDown].startdateminute ,  
                            [@AuditorIndividualDrillDown].enddateminute  
                  FROM      @AuditorIndividualDrillDown  
                            LEFT OUTER JOIN @AuditorIndividualStats ON [@AuditorIndividualStats].fullName = [@AuditorIndividualDrillDown].fullName  
                  WHERE     [@AuditorIndividualDrillDown].[index] = 3  
                  UNION  
                  SELECT    2 sortOrder ,  
                            102 [index] ,  
                            userName + '<br/> &nbsp;' headerName ,  
                            '' className ,  
                            userName ,  
                            fullName ,  
                            lName ,  
                            IsMiscellaneous ,  
                            startDate ,  
                            genTotalHours ,  
                            genExpectedHours ,  
                            genTotalPay ,  
                            genAvgPayPerHour ,  
                            desTotalHours ,  
                            desTotalDesigns ,  
                            desTotalCharacters ,  
                            desDesignsPerHour ,  
                            desCharPerHour ,  
                            desCostPerDesign ,  
                            keyTotalHours ,  
                            keyDesignsCleaned ,  
                            keyDesignsPerHour ,  
                            keyCostPerDesign ,  
                            less20TotalHours ,  
                            less20DesignsCleaned ,  
                            less20DesignsPerHour ,  
                            less20CostPerDesign ,  
                            MathTest ,  
                            mathAccuracy ,  
                            numberMatching ,  
                            numberAccuracy ,  
                            wordMatching ,  
                            wordAccuracy ,  
                            typingSpeed ,  
                            typingAccuracy ,  
                            typingTestKeyStrokes ,  
                            jobSpecQues ,  
                            beaconScore ,  
                            ficoScore ,  
                            [@AuditorIndividualStats].totalCall ,  
                            [@AuditorIndividualStats].totalCallIn ,  
                            [@AuditorIndividualStats].totalCallOut ,  
                            [@AuditorIndividualStats].totalCallInt ,  
                            [@AuditorIndividualStats].avgCalls ,  
                            [@AuditorIndividualStats].avgCallDurationMin ,  
                            [@AuditorIndividualStats].dailyStart ,  
                            [@AuditorIndividualStats].dailyEnd ,  
                            [@AuditorIndividualStats].totalActiveHours ,  
                            [@AuditorIndividualStats].nonWorkHours ,  
                            [@AuditorIndividualStats].keyStroke ,  
                            [@AuditorIndividualStats].totalEmails ,  
                            [@AuditorIndividualStats].startdateminute ,  
                            [@AuditorIndividualStats].enddateminute  
                  FROM      @AuditorIndividualStats  
                  WHERE     [index] = 101  
                ) AS AuditorIndividualNAvg;    
                
                
                    
        SELECT  *  
        FROM    #AuditorActivity  
        UNION  
        SELECT  3 sortOrder ,  
          5 [index] ,  
                'DIFFERENCE' headerName ,  
                '' className ,  
                '' userName ,  
                '' fullName ,  
                '' lName ,  
                0 isMiscellaneous ,  
                '' startDate ,  
                *  
        FROM    ( SELECT    ( IndRow.genTotalHours - AvgRow.genTotalHours ) genTotalHours ,  
                            ( IndRow.genExpectedHours  
                              - AvgRow.genExpectedHours ) genExpectedHours ,  
                            ( IndRow.genTotalPay - AvgRow.genTotalPay ) genTotalPay ,  
                            ( IndRow.genAvgPayPerHour  
                              - AvgRow.genAvgPayPerHour ) genAvgPayPerHour ,  
                            ( IndRow.desTotalHours - AvgRow.desTotalHours ) destotalHours ,  
                            ( IndRow.desTotalDesigns - AvgRow.desTotalDesigns ) desTotalDesigns ,  
                            ( IndRow.desTotalCharacters  
                              - AvgRow.desTotalCharacters ) desTotalCharacters ,  
                            ( IndRow.desDesignsPerHour  
                              - AvgRow.desDesignsPerHour ) desDesignsPerHour ,  
                            ( IndRow.desCharPerHour - AvgRow.desCharPerHour ) desCharPerHour ,  
                            ( IndRow.desCostPerDesign  
                              - AvgRow.desCostPerDesign ) desCostPerDesign ,  
                            ( IndRow.keyTotalHours - AvgRow.keyTotalHours ) keyTotalHours ,  
                            ( IndRow.keyDesignsCleaned  
                              - AvgRow.keyDesignsCleaned ) keyDesignsCleaned ,  
                            ( IndRow.keyDesignsPerHour  
                              - AvgRow.keyDesignsPerHour ) keyDesignsPerHour ,  
                            ( IndRow.keyCostPerDesign  
                              - AvgRow.keyCostPerDesign ) keyCostPerDesign ,  
                            ( IndRow.less20TotalHours  
                              - AvgRow.less20TotalHours ) less20TotalHours ,  
                            ( IndRow.less20DesignsCleaned  
                              - AvgRow.less20DesignsCleaned ) less20DesignsCleaned ,  
                            ( IndRow.less20DesignsPerHour  
                              - AvgRow.less20DesignsPerHour ) less20DesignsPerHour ,  
                            ( IndRow.less20CostPerDesign  
                              - AvgRow.less20CostPerDesign ) less20CostPerDesign ,  
                            ( IndRow.MathTest - AvgRow.MathTest ) MathTest ,  
                            ( IndRow.mathAccuracy - AvgRow.mathAccuracy ) mathAccuracy ,  
                            ( IndRow.numberMatching - AvgRow.numberMatching ) numberMatching ,  
                            ( IndRow.numberAccuracy - AvgRow.numberAccuracy ) numberAccuracy ,  
                            ( IndRow.wordMatching - AvgRow.wordMatching ) wordMatching ,  
                            ( IndRow.wordAccuracy - AvgRow.wordAccuracy ) wordAccuracy ,  
                            ( IndRow.typingSpeed - AvgRow.typingSpeed ) typingSpeed ,  
                            ( IndRow.typingAccuracy - AvgRow.typingAccuracy ) typingAccuracy ,  
                            ( IndRow.typingTestKeyStrokes  
                              - AvgRow.typingTestKeyStrokes ) typingTestKeyStrokes ,  
                            ( IndRow.jobSpecQues - AvgRow.jobSpecQues ) jobSpecQues ,  
                            ( IndRow.beaconScore - AvgRow.beaconScore ) beaconScore ,  
                            ( IndRow.ficoScore - AvgRow.ficoScore ) ficoScore ,  
                            ( IndRow.totalCall - AvgRow.totalCall ) totalCall ,  
                            ( IndRow.totalCallIn - AvgRow.totalCallInt ) totalCallIn ,  
                            ( IndRow.totalCallOut - AvgRow.totalCallOut ) totalCallOut ,  
                            ( IndRow.totalCallInt - AvgRow.totalCallInt ) totalCallInt ,  
                            ( IndRow.avgCalls - AvgRow.avgCalls ) avgCalls ,  
                            ( IndRow.avgCallDurationMin  
                              - AvgRow.avgCallDurationMin ) avgCallDurationMin ,  
                            CAST(IndRow.startdateminute  
                            - AvgRow.startdateminute AS VARCHAR(10)) + ' min' dailyStart ,  
                            CAST(IndRow.enddateminute - AvgRow.enddateminute AS VARCHAR(10))  
                            + ' min' dailyEnd ,  
                            ( IndRow.totalActiveHours  
                              - AvgRow.totalActiveHours ) totalActiveHours ,  
                            ( IndRow.nonWorkHours - AvgRow.nonWorkHours ) nonWorkHours ,  
                            ( IndRow.keyStroke - AvgRow.keyStroke ) keyStroke ,  
                            ( IndRow.totalEmails - AvgRow.totalEmails ) totalEmails ,  
                            ( IndRow.startdateminute - AvgRow.startdateminute ) startdateminute ,  
                            ( IndRow.enddateminute - AvgRow.enddateminute ) enddateminute  
                  FROM      #AuditorActivity IndRow ,  
                            #AuditorActivity AvgRow  
                  WHERE     IndRow.[sortOrder] = 1  
                            AND AvgRow.[sortOrder] = 2  
                ) AS DifferenceRow;      
                     
    END;  
GO
