CREATE TABLE [dbo].[KeyStats_WHD_ClosedTickets_Snapshot]
(
[TicketID] [int] NULL,
[Tech_Guid] [uniqueidentifier] NULL,
[Tech_UID] [int] NULL,
[Tech_UName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tech_FullName] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tech_FName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tech_LName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tech_StartDate] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Tech_IsMisc] [bit] NULL,
[Tech_UniqueUserId] [int] NULL,
[UnassignedTime] [decimal] (18, 0) NULL,
[FirstResponseTime] [decimal] (18, 0) NULL,
[TotalTimeOpen] [decimal] (18, 0) NULL,
[TotalTimeWorked] [float] NULL,
[PeopleCcPerTicket] [decimal] (18, 0) NULL,
[ReassignmentsCount] [int] NULL,
[PastDueAlerts] [int] NULL,
[TotalNoofTechNotes] [int] NULL,
[Evaluation] [decimal] (18, 0) NULL,
[StatusType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClosedDate] [datetime] NULL,
[AssignedTech] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ClientName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ProblemType] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Subject] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LocationName] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportedDate] [datetime] NULL,
[ReopenCounter] [int] NULL,
[SnapshotDate] [datetime] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
