CREATE TABLE [dbo].[KeyStats_AcceptedOpportunity_HourlySnapshot]
(
[opid] [uniqueidentifier] NOT NULL,
[Appid] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[name] [varchar] (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consultant] [varchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[consultantId] [uniqueidentifier] NOT NULL,
[companyName] [varchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[acceptanceDate] [datetime2] (2) NULL,
[leaseAmt] [money] NULL,
[FundingMethodValue] [tinyint] NULL,
[FundingMethod] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[initialCash] [money] NULL,
[NetVendorAmount] [money] NULL,
[securityDeposit] [money] NULL,
[Payment] [money] NULL,
[purchaseOption] [money] NULL,
[EquipmentCost] [money] NULL,
[TotalReferralFee] [money] NULL,
[TotalReferralFeePts] [float] NULL,
[CreditManager] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditManagerid] [uniqueidentifier] NULL,
[oneoffProfit] [money] NULL,
[oneoffProfitPts] [float] NULL,
[IRR] [float] NULL,
[AVGBeaconScore] [int] NULL,
[AVGFICOScore] [int] NULL,
[tib] [decimal] (8, 2) NULL,
[paydex] [int] NULL,
[repeatclient] [int] NULL,
[insideSales] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[insideSalesId] [uniqueidentifier] NULL,
[SD_Eligible] [bit] NULL,
[PO_Eligible] [bit] NULL,
[isTitled] [bit] NOT NULL,
[equipmentType] [varchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[New_LeaseAdministratorId] [uniqueidentifier] NULL,
[New_LeaseAdministratorIdName] [varchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[oppStatus] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[distributionmethod] [varchar] (150) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[NoOfEnvelopesSent] [int] NULL,
[DocsPendingDate] [datetime2] (2) NULL,
[DocsSent] [datetime2] (2) NULL,
[DocumentsReceivedDate] [datetime2] (2) NULL,
[InitialPurchaseOrderDate] [datetime2] (2) NULL,
[ContractType] [tinyint] NULL,
[NoOfDocsAdded] [int] NULL,
[NoOfDocsRemoved] [int] NULL,
[OtherIncomeExpense] [money] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KeyStats_AcceptedOpportunity_HourlySnapshot] ADD CONSTRAINT [PK_KeyStats_AcceptedOpportunity_HourlySnapshot] PRIMARY KEY CLUSTERED  ([opid]) ON [PRIMARY]
GO
