CREATE TABLE [dbo].[KeyStats_Repo_AllOpenReposAssets_DailySnapShot]
(
[new_repoid] [uniqueidentifier] NOT NULL,
[new_repoappid] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[RepoTypeValue] [int] NULL,
[RepoType] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_topic] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[repoStatusCode] [int] NULL,
[RepoStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_repoassetid] [uniqueidentifier] NOT NULL,
[AssetID] [int] NULL,
[AssetNo] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[EquipmentCategoryValue] [int] NULL,
[EquipmentCategory] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[New_OwnershipType] [int] NULL,
[AssetRelationship] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[new_year] [int] NULL,
[new_make] [nvarchar] (50) COLLATE Latin1_General_CI_AS NULL,
[new_model] [nvarchar] (100) COLLATE Latin1_General_CI_AS NULL,
[new_description] [nvarchar] (250) COLLATE Latin1_General_CI_AS NULL,
[new_salestage] [int] NULL,
[salestageStatus] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[OrigEquip] [money] NULL,
[DefaultBV] [decimal] (38, 6) NOT NULL,
[estimatedsalesprice] [money] NOT NULL,
[equ_id] [int] NULL,
[List] [money] NOT NULL,
[ContractPendingFlag] [int] NOT NULL,
[IsChildAsset] [int] NOT NULL,
[SALEPRICE] [money] NULL,
[EUCommission] [money] NULL,
[ProratedExpenses] [decimal] (38, 6) NOT NULL,
[ProratedMiscExpensesCredits] [decimal] (38, 6) NOT NULL,
[ProratedSettlementCost] [decimal] (38, 6) NOT NULL,
[SalesCommissionType] [varchar] (28) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[ProratedSalesCommission] [decimal] (38, 6) NULL,
[owneridname] [nvarchar] (160) COLLATE Latin1_General_CI_AS NULL,
[closedon] [date] NULL,
[CustomerState] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerStatecode] [int] NULL,
[createdon] [datetime] NULL,
[Collector] [nvarchar] (200) COLLATE Latin1_General_CI_AS NULL,
[CollectorGUID] [uniqueidentifier] NULL,
[CreditManagerGUID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditManager] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesPersonGUID] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesPerson] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
