CREATE TABLE [dbo].[KeyStats_Repo_ClosedRepos_DailySnapShot]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[RepoID] [uniqueidentifier] NOT NULL,
[Topic] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[AccountID] [uniqueidentifier] NULL,
[CompanyName] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DBA] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeaseNumber] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerState] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Legal] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[EquipTypes] [nvarchar] (250) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Type] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TypeValue] [int] NULL,
[statuscode] [int] NULL,
[Status] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesStageCode] [int] NULL,
[SalesStage] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalAssets] [int] NULL,
[TotalAssetsSold] [int] NULL,
[AssetSoldPct] [float] NULL,
[ListPrice] [money] NULL,
[estimatedsalesprice] [money] NULL,
[BVDefault] [money] NULL,
[EquipmentCost] [money] NULL,
[BVCost] [money] NULL,
[GainLoss] [money] NULL,
[NetGainLoss] [money] NULL,
[ownerid] [uniqueidentifier] NULL,
[owneridname] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[closedon] [datetime] NULL,
[new_repostartdate] [datetime] NULL,
[repoDays] [int] NULL,
[totalExpenses] [money] NULL,
[miscexpensescredits] [money] NULL,
[breakeven] [money] NULL,
[proceedsfromsale] [money] NULL,
[TotalSalesCommission] [money] NULL,
[profitopportunitycommission] [money] NULL,
[OriginalBeaconScore] [int] NULL,
[OriginalFicoScore] [int] NULL,
[RepoBeaconScore] [int] NULL,
[RepoFicoScore] [int] NULL,
[tib] [int] NULL,
[paydex] [int] NULL,
[CollectorGUID] [uniqueidentifier] NULL,
[Collector] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreatedOn] [datetime] NULL,
[oldestrentdue] [datetime] NULL,
[DaysPastDueatRepo] [int] NULL,
[ModifiedOn] [datetime] NULL,
[ListDate] [datetime] NULL,
[SoldDate] [datetime] NULL,
[ActualPickupDate] [datetime] NULL,
[ScheduledPickupDate] [datetime] NULL,
[TransferableTitleDate] [datetime] NULL,
[AssetCreatedOnDate] [datetime] NULL,
[settlementreceived] [money] NULL,
[PaymentRemaining] [int] NULL,
[PaymentMade] [int] NULL,
[LastPaymentReceivedDate] [datetime] NULL,
[IRR] [float] NULL,
[AmountFinanced] [money] NULL,
[TotalTerm] [int] NULL,
[salesCommission] [money] NULL,
[commissionPayBack] [money] NULL,
[numOfCollectorComments] [int] NULL,
[SharedCredit1Guid] [uniqueidentifier] NULL,
[SharedCredit1] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SnapshotDate] [datetime] NOT NULL CONSTRAINT [DF_SalesRanking_ClosedRepos_DailySnapShot_SnapshotDate] DEFAULT (getdate()),
[SalesPersonGUID] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SalesPerson] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StateCode] [bit] NULL,
[CreditManagerGUID] [nvarchar] (160) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CreditManager] [nvarchar] (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[KeyStats_Repo_ClosedRepos_DailySnapShot] ADD CONSTRAINT [PK_SalesRanking_ClosedRepos_DailySnapShot] PRIMARY KEY CLUSTERED  ([ID]) ON [PRIMARY]
GO
