CREATE TABLE [dbo].[SalesRanking_CollectorPortfolioRepot_SnapShot]
(
[ID] [int] NOT NULL IDENTITY(1, 1),
[BankName] [varchar] (21) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CustomerName] [varchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[LeaseNumber] [varchar] (15) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[Cust#] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[StartDate] [datetime] NULL,
[EquipCost] [numeric] (11, 2) NULL,
[DownPaymenttoBeacon] [numeric] (11, 2) NULL,
[RentPayment] [numeric] (11, 2) NULL,
[SalesTax] [numeric] (11, 2) NULL,
[TotalPayment] [numeric] (11, 2) NULL,
[PaymentsReceived] [numeric] (3, 0) NULL,
[PaymentsLeft] [numeric] (3, 0) NULL,
[NextInvDate] [datetime] NULL,
[OldestRentDue] [datetime] NULL,
[daysLate] [int] NULL,
[RemainingtobeBilled] [numeric] (11, 2) NULL,
[OutstandingBalance] [numeric] (11, 2) NULL,
[TotalReceivableBalance] [numeric] (12, 2) NULL,
[LateFeeDue] [numeric] (11, 2) NULL,
[ResidPercent] [numeric] (26, 14) NULL,
[ResidPO] [numeric] (12, 2) NULL,
[RealIRR] [numeric] (9, 5) NULL,
[AccountDistCode] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[TotalRent] [numeric] (15, 2) NULL,
[DollarWeightedRent] [numeric] (25, 7) NULL,
[Code] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[BookValue] [numeric] (11, 2) NULL,
[LeaseStatus] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeaseType] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[LeaseTypeID] [int] NULL,
[MelcoAB] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Dtate] [varchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[FMV] [varchar] (25) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SecurityDepositAmt] [numeric] (11, 2) NULL,
[Maturity] [int] NULL,
[Collector] [varchar] (7) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[CollectorName] [varchar] (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[uid] [uniqueidentifier] NULL,
[defaultedLease] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lp_vendorcompany] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lp_vendorno] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[crm_vendorno] [varchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[lease_term] [numeric] (18, 0) NULL,
[lease_term_date] [datetime] NULL,
[lease_posted] [char] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[totalPayments] [numeric] (6, 0) NULL,
[lease_comp_num] [varchar] (2) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
[lease_disc_type] [varchar] (1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SnapShotDate] [datetime] NULL,
[LeaseRenewTranCode] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ReportDate] [date] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
